swagger: '2.0'
info:
  version: 1.0.0
  title: jKool API
  description: jKool API
  termsOfService: 'https://www.jkoolcloud.com/company/terms-conditions/'
  contact:
    name: Charley Rich
    email: crich@jkoolcloud.com
    url: www.jkoolcloud.com
  license:
    name: jKool
    url: 'https://www.jkoolcloud.com/company/privacy-policy/'
host: 'data.jkoolcloud.com:6580'
basePath: /jKool/JKool_Service
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /event:
    post:
      description: Creates an event
      operationId: postEvent
      produces:
        - application/json
      parameters:
      - name: event
        description: the event
        required: true
        in: body
        schema:
          $ref: '#/definitions/event'
      - name: token
        in: header
        description: token to be passed as a header
        required: true
        type: string
      responses:
        '200':
          description: Event streamed properly.
        '202':
          description : Event accepted.    
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '405':
          description: Method not allowed.          
        '500':
          description: Internal Server Error.
        '501':
          description: Not implemented.       
        '500':
          description: Internal Server Error        
        default: 
          description: Bad Request. 
  /activity:
    post:
      description: Creates an activity
      operationId: postActivity
      produces:
        - application/json
      parameters:
      - name: activity
        description: the activity
        required: true
        in: body
        schema:
          $ref: '#/definitions/activity'
      - name: token
        in: header
        description: token to be passed as a header
        required: true
        type: string
      responses:
        '200':
          description: Event streamed properly.
        '202':
          description : Event accepted.    
        '400':
          description: Bad Request.
        '401':
          description: Unauthorized.
        '405':
          description: Method not allowed.          
        '500':
          description: Internal Server Error.
        '501':
          description: Not implemented.       
        '500':
          description: Internal Server Error        
        default: 
          description: Bad Request. 
definitions:
  event:
    required:
      - source-fqn
      - tracking-id
      - time-usec
    properties:
      tracking-id:
        type: string
        description: Identifies the data being exchanged. This identifier can be shared among events if they are operating on the same data.
      corr-id:
        type: string
        description: An identifier of another event that this event correlates to.
      exception:
        type: string
        description: Reason for a failed event.
      resource:
        type: string
        description: A resource the event acted upon. i.e. a queue or file.
      wait-time-used:
        type: integer
        format: int32
        description: If a blocking operation, how long the event was waiting for the data to appear.
      source-fqn:
        type: string
        description: Identifies very specifically where the event came from. Must be in a special format. Please see documentation.
      source-url:
        type: string
        description: URL that sourced this event. For example, if the event came from a browser.
      severity:
        type: string
        description: Severity of the event. Defaults to SUCCESS. Please see documentation for valid entries.
      type:
        type: string
        description: Type of record. Please see documentation for valid entries.
      pid:
        type: integer
        format: int32
        description: Process identifier.
      tid:
        type: integer
        format: int32
        description: Thread identifier.
      comp-code:
        type: string
        description: Completion code.
      reason-code:
        type: integer
        format: int32
        description: Numeric reason for the event.
      location:
        type: string
        description: Location of the event. This can be a Geo Location, file number, etc.
      operation:
        type: string
        description: Name of the event.
      user:
        type: string
        description: User associated with the event.
      time-usec:
        type: string
        format: date-time
        description: Time this event is reported.
      start-time-usec:
        type: string
        format: date-time
        description: Time the event began.
      end-time-usec:
        type: string
        format: date-time
        description: Time the event completed.
      elapsed-time-usec:
        type: integer
        format: int32
        description: Elapsed time between when the event began and when it ended.
      snap-count:
        type: integer
        format: int32
        description: Number of snapshots in the event.
      msg-text:
        type: string
        description: Event message.
      msg-size:
        type: integer
        format: int32
        description: Message size.
      encoding:
        type: string
        description: Message encoding.
      charset:
        type: string
        description: Message character set.
      mime-type:
        type: string
        description: Message mime type.
      msg-age:
        type: integer
        format: int32
        description: Message age how long message was waiting to be processed. Pertains to JMS or other types of messaging.
      msg-tag:
        type: string
        description: Message search label.
      parent-tracking-id:
        type: string
        description: Unique identifier of the parent activity.
      snapshots:
        type: array
        items:
         $ref: '#/definitions/snapshot'
        description: List of categorized custom fields for this event.  
  snapshot:
    required:
      - name
      - time-usec
    type: object
    properties:
      name:
        type: string
        description: Name of the category of custom fields.
      type:
        type: string
        description: Must be SNAPSHOT.
      track-id:
        type: string
        description: Unique identifier for the snapshot.
      parent-id:
        type: string
        description: The unique identifier of the snapshots parent event.
      count:
        type: integer
        format: int32
        description: Number of properties (custom fields) in this category of custom fields.
      time-usec:
        type: string
        format: date-time
        description: Time this category of fields occurred.
      category:
        type: string
        description: A "super"-category. A higher grouping of snapshots.  Multiple snapshots can belong to the same super-category.
      properties:
        type: array
        description: The custom fields that belong to this category of fields.
        items:
          $ref: '#/definitions/property'
  property:
    required:
      - name
      - type
      - value
    type: object
    properties:
       name:
        type: string
        description: Name of the custom field.
       type:
        type: string
        description: Data type of the custom field.
       value:
        type: string
        description: Value of custom field.
  activity:
    required:
      - tracking-id
      - operation
      - time-usec
      - status
    properties:
      tracking-id:
        type: string
        description: The unique identifier of this activity.
      type:
        type: string
        description: Must be ACTIVITY.
      operation:
        type: string
        description: The name of this activity.
      time-usec:
        type: string
        format: date-time
        description: Time this activity is reported.
      status:
        type: string
        description: The status of this activity. Please see documentation for details.
      source-fqn:
        type: string
        description: Identifies where the activity came from. Must be in a special format. Please see documentation.